Popup mobile desktop
binodbhusal/Portfolio pull request #12
Opened 2023-04-14 13:11 UTC by binodbhusal

**The following changes were made:**
- Added Popup menu to both mobile and desk versions of the profile.
- Created object variables to store data and made it dynamic.

2023-04-14 13:56 UTC, AnselemOdims requested changes
### Hi @binodbhusal , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-14 13:56 UTC, AnselemOdims commented on index.html
- [ ] According to the instructions, the project's section should be created dynamically, this means you should remove all project cards from the HTML and generate them with Javascript when the page loads. Please kindly help fix this

2023-04-14 13:56 UTC, AnselemOdims commented on style.css
> +
- [ ] At the moment, your modal popup design is not responsive. Please kindly ensure that your implementation is responsive and follows the design guidelines(spacing, font, etc)

### Your Design
![image](https://user-images.githubusercontent.com/43995830/232064027-2ee421d7-1328-4e00-81a1-568ecfe956ad.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/232064224-8dba1968-1e13-4be9-b587-846d5e45685d.png)

2023-04-14 22:52 UTC, binodbhusal commented
**The following changes were made**
-  project's section was created dynamically, removed all project cards from the HTML, and generated them with Javascript when the page loads. 
- Created separate popup card - desktop and mobile screen size if click on see project button click mobile size card will open click on the desktop see project button desktop size will open.

2023-04-14 23:15 UTC, binhussen requested changes
Hi @binodbhusal , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 23:15 UTC, binhussen commented on style.css
> +    width: 100vw;
- Kindly, your mobile popup is overflowing because you used fixed `width` with `margin left` and `margin right`, please fix it by using `max-width` instead of `width` to improve user experience 👍 
- Please, add some margin from the top to stick the Figma design and have a better UI 👍
![2023-04-15_02-13](https://user-images.githubusercontent.com/52010789/232169217-b1caf8f2-be30-4af3-b21e-c4ee62ea4b30.png)

2023-04-14 23:35 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @binodbhusal 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 23:35 UTC, anagudelogu commented on style.css
> +  }
- [ ] Great job applying the changes requested by the previous reviewer! 🚀 However, there's still one missing and is adding some margin-top to your popup. Please consider adding it in order to match the FIGMA design! 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/232170636-e89eef8b-f9d8-4c8c-a292-62e986fd2f0c.png) |![image](https://user-images.githubusercontent.com/77069011/232170603-ca4c21d0-6693-447e-958f-ec5a9f888ea0.png) |

- [ ] **[OPTIONAL]** Please consider fixing the close icon too! as you see it doesn't match the design. 🤓 🔧

2023-04-15 01:07 UTC, binhussen requested changes
Hi @binodbhusal , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 01:07 UTC, binhussen commented on style.css
> +    margin: auto; /* center the popup horizontally */
- kindly, add Mergin top here by modifying `margin: 24px auto;` to stick the Figma design 👍

2023-04-15 01:07 UTC, binhussen commented on style.css
> +    top: -25px;
- Kindly, here also update the close button by modifying the `top` to stick the Figma design 👍

2023-04-15 07:33 UTC, TadesseDev approved these changes
### Hi @binodbhusal 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 11:51 UTC, merged