Completed Portfolio Desktop Version
binodbhusal/Portfolio pull request #5
Opened 2023-03-30 16:00 UTC by binodbhusal

**The following changes were made in this project:**
   - Modified nav bar as per desktop version screen min width 768px.
   - Added content and images using a grid layout.
   - Modified about myself section and added short information, images, skills, and languages.
   - Modified contact form.

2023-03-30 18:18 UTC, tsohleDev requested changes
## Hi Micronauts @binodbhusal  and @SolomonTheCoder 

Good job so far!
There are some issues that you still need to work on.

![163947610-e4d849d5-e69c-49b9-90bd-a4191f4e2856](https://user-images.githubusercontent.com/97100091/191558701-8ed50201-3123-435c-89d8-29edcb66c64d.gif)

## Highlights!
- README template ✔️ 
- Descriptive commits ✔️ 
- Good branch name  ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- All requirements met ❌

Hello ✋, you have done well creating your project 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

## Compliment
_Every comment with the [COMPLIMENT] prefix is not  a request, just a compliment at your skills_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@tsohleDev` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 18:18 UTC, tsohleDev commented on index.html
[COMPLIMENT] I wanna applaud you on how your page looks, I like how each section fills the screen making the transition from one section to another apparent 👏 💯

2023-03-30 18:18 UTC, tsohleDev commented on style.css
- [ ] I think it would be better if you also included the background image as CSS, because currently there is no background, since you you are following a design its always best to implement all the aspects of it 😉 

|Your design|Figma design|
| --- | --- |
| ![yours](https://user-images.githubusercontent.com/102636489/228925044-5b59f5b9-deea-4d9b-b91c-918e0df9a5a6.png) | ![design](https://user-images.githubusercontent.com/102636489/228925165-5b2f17f4-3ef2-48b3-9a91-5366bc0b5456.png) |

2023-03-30 18:18 UTC, tsohleDev commented on style.css
- [ ] I noticed that now your mobile ``header`` doesn't have the alignment that it had/should have, I kindly suggest that you ensure that when designing the desktop your mobile version still looks and acts as required 😉 

![mobile](https://user-images.githubusercontent.com/102636489/228925834-38970657-b4a8-462c-a37b-dab1c8badb7a.png)

2023-03-30 18:18 UTC, tsohleDev commented on style.css
[OPTIONAL] I suggest that for your mobile version, you use **responsive units for the widths and sizes of the cards and sections** because modern mobile devices have varying screen sizes and you wouldn't want to have your app viewing in an unintentional manner on a certain a screen size 😉 


## Some screen sizes your app breaks
|![f1](https://user-images.githubusercontent.com/102636489/228927264-b321f230-b1a3-4014-a54d-30b61cd3cd2b.png)|![f2](https://user-images.githubusercontent.com/102636489/228927313-29fc92e1-ad1b-41ab-b066-0ac5ed088581.png)|
| --- | --- |
|![f3](https://user-images.githubusercontent.com/102636489/228927426-ffa971af-a0ba-491f-b540-b1a349f9d3ff.png)|![f4](https://user-images.githubusercontent.com/102636489/228927542-bb44116f-1e7a-4113-a749-21f074fe5129.png)|

2023-03-31 10:51 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 
Hi @binodbhusal , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
-  All requested changes implemented :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-03 19:36 UTC, merged